### ISSUE TITLE
Re implement BASE_HREF in backend and frontend

### ISSUE THREAD

**Issue by myonara** [mystiker/webmud3#39]
Before the refactoring the backend and frontend could be served as a subdirectory within a domain, three examples:
* https://www.unitopia.de/webmud3/
* https://www.unitopia.de/webmud3test/orbit
* https://seifenblase.de/webmud3/

In the frontend it was done with either manual entry and reeplacement of BASE_HREF in the index.html (in the beginning of the project) or a base_href service, which detects the right prefix/configuration from the current path (current master branch).

**Comment by mystiker** [comment]
Changing the base-href in index.html from "/" to "./" should work 99% of the time. Have a look at

https://angular.dev/guide/routing/common-router-tasks
and
https://symflower.com/en/company/blog/2021/path-independent-angular/

Lets try this. We can fall back to adding the path during build via the --base-href flag, if we encounter issues.
